<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-DonaldsonMotors" Class="CalendarDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=aspnet-DonaldsonMotors;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bookings" Member="Bookings">
    <Type Name="Booking">
      <Column Name="BookingId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BookingDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CheckIn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Cancelled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CancelationReason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EstimatedCost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Deposit" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Complete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TotalCost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CustId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
    </Type>
  </Table>
</Database>